apiVersion: v1
kind: Namespace
metadata:
  name: vm-demo
  labels:
    bgp-enabled: "true"
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: test-vm1
  namespace: vm-demo
  labels:
    kubevirt.io/vm: test-vm1
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/vm: test-vm1
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: containerdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - name: default
            masquerade: {}
          - name: secondary
            bridge: {}
        resources:
          requests:
            memory: 1Gi
      networks:
      - name: default
        pod: {}
      - name: secondary
        multus:
          networkName: vm-bgp-network
      volumes:
      - name: containerdisk
        containerDisk:
          image: quay.io/containerdisks/fedora:39
      - name: cloudinitdisk
        cloudInitNoCloud:
          networkData: |
            version: 2
            ethernets:
              eth1:
                dhcp4: true
          userData: |
            #cloud-config
            password: fedora
            chpasswd: { expire: False }
            ssh_pwauth: True
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: test-vm2
  namespace: vm-demo
  labels:
    kubevirt.io/vm: test-vm2
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/vm: test-vm2
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: containerdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - name: default
            masquerade: {}
          - name: secondary
            bridge: {}
        resources:
          requests:
            memory: 1Gi
      networks:
      - name: default
        pod: {}
      - name: secondary
        multus:
          networkName: vm-bgp-network
      volumes:
      - name: containerdisk
        containerDisk:
          image: quay.io/containerdisks/fedora:39
      - name: cloudinitdisk
        cloudInitNoCloud:
          networkData: |
            version: 2
            ethernets:
              eth1:
                dhcp4: true
          userData: |
            #cloud-config
            password: fedora
            chpasswd: { expire: False }
            ssh_pwauth: True
